name: SpellArticles
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test-pr-review:
    if: github.event_name == 'pull_request'
    name: runner / languagetool (github-pr-review)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./pages/blog/"
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: info
          patterns: "**.md"
          custom_api_endpoint: https://languagetool.org/api
